# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c13294543da234a863a5e0da5305730caef150ef739a413341d26fe990d0bc95323d3a040e21537f15367e271c80cab90a0152a154708f5829f7d1c95bda1a99

test:
  secret_key_base: d9595a59625202a846222b708af8bb7a4b5b61d0f813ffb9156cd86b27b9e8b978b3771f034229782a12c21ea6bc9c50c0db6a7d053c768350f9b3fcaf52368e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
